const fs = require('fs')
const startTime = performance.now();

// PART 2 AoC2023

fs.readFile('./input.txt', 'utf8', (err, data) => {
  if(err) return console.error(err);

  //Value is number contained in number word to be able to replace number in 2 number words with a common letter allowing to replace the second number word
  const stringNumbers = {
    one: 'o1ne',
    two: 't2wo',
    three: 't3hree',
    four: 'f4our',
    five: 'f5ive',
    six: 's6ix',
    seven: 's7even',
    eight: 'e8ight',
    nine: 'n9ine'
  }

  const convertedData = data.split(/[\r\n]+/);

  // Iterate over the line passed in replacing number words by their key/value
  const reduceReplace = (line, [key, value]) => line.replaceAll(key, value)

  const parsedData = convertedData.map((line) => {

  // Pass the array of pair key/value generated by Object.entries to iterate over the line passed in.
  const wordsToNumberArray = Object.entries(stringNumbers).reduce(reduceReplace, line);
  const numbersArray = wordsToNumberArray.split('').filter(e => !isNaN(e));
    
  return `${numbersArray[0]}${numbersArray[numbersArray.length-1]}`
  })

  console.log(`The sum for the calibration is ${parsedData.reduce((acc, curr) => +curr + acc, 0)}`);

})

const endTime = performance.now()
console.log(`Time taken : ${parseFloat(endTime - startTime, 2).toFixed(2)}ms`)
